### ISSUE TITLE
Revert back to version 0.6

### ISSUE THREAD

**Issue by RichardMorris** [bgromov/wiki-mathjax#11]
Wikipedia has now withdrawn support for client side MathJax. Can you revert back to the version which did not rely on this version.

**Comment by bgromov** [comment]
Can you please elaborate more on your problem? I see no issues with this extension so far.

**Comment by RichardMorris** [comment]
Yes it does seem to look alright. I think my preferences were set wrong and it seems to need PNG mode. I've a feeling they may drop that node at some point in the future.

**Comment by RichardMorris** [comment]
The PNG removal task is here: https://phabricator.wikimedia.org/T74240 This would break this extension.

**Comment by bgromov** [comment]
Oh, I see what you mean now. But then either MathJax or some other vectorized rendering will be used and we will not need the extension at all.

Nevertheless, the Wikimedia config is now embedded to the extension (see [texvc.js](https://github.com/bgromov/wiki-mathjax/blob/master/texvc.js)), so this PNG removal task should not affect functionality. Some of these settings have been used for a long time. I just made them more consistent in the last release.

**Comment by RichardMorris** [comment]
There is a bit of a battle over the future of MathJax on wikipedia at the moment. https://phabricator.wikimedia.org/T99369 The devs don't want to support MathJax anymore instead preferring a MathML/SVG solution. Alas both don't look as good as MathJax, so there might be more people using extension. I've mentioned it at https://en.wikipedia.org/wiki/Wikipedia_talk:WikiProject_Mathematics.

What might be nice is if it triggers when using the raw LaTeX preference option.
