### ISSUE TITLE
\R and \C, .... in wikipedia

### ISSUE THREAD

**Issue by FlorianPfaff** [bgromov/wiki-mathjax#20]
Hello,

firstoff, I really like the extension. But I am frequently noticing one issue: Among others, \R and \C which should be rendered as \mathbb{R} and \mathbb{C} in Wikipedia, simply appear red. Maybe there is some easy change that can be done, e.g., replacing all \R by \mathbb{R} and \C by \mathbb{C}, \N by \mathbb{N}, \Z by \mathbb{Z} before passing it on to MathJax - that would be very nice.

Cheers!

**Comment by bgromov** [comment]
Thanks for the report. Could you please give the links to problematic pages? I went through [Wikipedia's list](https://en.wikipedia.org/wiki/Help:Displaying_a_formula) of math symbols and couldn't find the ones you've mentioned.

Thanks

**Comment by FlorianPfaff** [comment]
Sorry, I should have thought of including an example. \R, \Q, \Z, and \N are used, e.g., inhttps://de.wikipedia.org/wiki/Reelle_Zahl
It is not limited to the German Wikipedia, however. Here is one example from the English Wikipedia
https://en.wikipedia.org/wiki/Expected_value
Rendering using the plugin:
![image](https://user-images.githubusercontent.com/6773539/37251592-6657672c-2513-11e8-8c61-dc44cba08c24.png)
Rendering without the plugin:
![image](https://user-images.githubusercontent.com/6773539/37251615-a9d386ac-2513-11e8-8138-a61a5db1c939.png)

Thanks already for your prompt reply and for considering to add support for these symbols!

**Comment by bgromov** [comment]
Unfortunately I can't reproduce the error. I can see the source equations (in Wikipedia editor) use the `\R` and alike, but apparently these are converted by the math engine into the proper `\mathbb {R}`. So, per your example I see the following source in the Wikipedia editor:

```
:<math>([1, +\infty), {\mathcal B}_{\R_{ [1, +\infty) }}, \lambda ),</math>
```
and in HTML (see `alt` field of the `<img>` tag):

```html
<img src="https://wikimedia.org/api/rest_v1/media/math/render/svg/9d62ca4aa43bd6224f7f8dd44ec659a2067a4c94"
class="mwe-math-fallback-image-inline"
aria-hidden="true" style="vertical-align: -1.338ex; width:21.171ex; height:3.343ex;"
alt="{\displaystyle ([1,+\infty ),{\mathcal {B}}_{\mathbb {R} _{[1,+\infty )}},\lambda ),}">
```
The text in `alt` is exactly what is used by the plugin. So for me everything renders properly.

Do you have any other extensions installed that amend the default Wikipedia appearance and may interfere with the `wiki-mathjax`?

**Comment by FlorianPfaff** [comment]
Hello,
I was able to confirm that it works on a fresh install with only the wiki-mathjax plugin loaded. After some trying around I finally identified what is causing the issues: It does not work correctly when I am logged in on Wikipedia.
There are 3 rendering options for LaTeX in the Wikipedia
* PNG images
* LaTeX source code
* MathML with SVG/PNG fallback
When selecting 1 or 3, I see the issue described. When choosing 2, all is rendered properly. So apparently, there is a solution to this problem.

So thanks for taking a look at this issue. I'm sorry I didn't try around more before reporting it, but I didn't think that such minor rendering problems could be fixed by changing around in settings. Feel free to close this issue, I just leave it open because you may want to add it to the known issues list before closing it.
Cheers!

**Comment by bgromov** [comment]
Thanks for the investigation!
