### ISSUE TITLE
Content Security Policy

### ISSUE THREAD

**Issue by FranklinYu** [bgromov/wiki-mathjax#22]
> `MathJax.js?config=TeX-AMS_HTML,Safe:19` [Report Only] Refused to load the script 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/config/TeX-AMS_HTML.js?V=2.7.1' because it violates the following Content Security Policy directive: "`script-src 'unsafe-eval' 'self' meta.wikimedia.org *.wikimedia.org *.wikipedia.org *.wikinews.org *.wiktionary.org *.wikibooks.org *.wikiversity.org *.wikisource.org wikisource.org *.wikiquote.org *.wikidata.org *.wikivoyage.org *.mediawiki.org 'unsafe-inline'`". Note that '`script-src-elem`' was not explicitly set, so '`script-src`' is used as a fallback.

I encounter this error on Wikipedia.

**Comment by bgromov** [comment]
Could you post the URL of the page please?

**Comment by FranklinYu** [comment]
Seems like this error doesn’t prevent formulae from being rendered. I would re-open if I find any example of breaking formula. Thanks!
