### ISSUE TITLE
Fix right-click menu

### ISSUE THREAD

**Issue by alexchandel** [bgromov/wiki-mathjax#23]
Right-clicking an equation always opens mathjax's context menu, even if it's already open, or if modifier keys are pressed.

Unfortunately Google refuses to add any "override" to JS context menus, so it's impossible to right-click and inspect the elements of any equations.

Could you disable the context menu if the shift+command keys are pressed?

**Comment by bgromov** [comment]
I don't think this is something everyone needs. If you need to use the element inspection tool, just press Cmd+Shift+C (on macOS, or similar on other platforms) to inspect element under the mouse cursor.
