### ISSUE TITLE
[bug] Doesn't work in edit mode.

### ISSUE THREAD

**Issue by alexchandel** [bgromov/wiki-mathjax#25]
This doesn't work when editing a page's source.  Using "Preview" will render a section when editing, and this extension doesn't parse any of the math elements.

**Comment by bgromov** [comment]
I can't reproduce your problem. Please provide the exact link and steps that lead to the issue.

**Comment by bgromov** [comment]
Closing for now, feel free to re-open.

**Comment by alexchandel** [comment]
Edit any page, like this one, and hit "Preview": https://en.wikipedia.org/w/index.php?title=Feynman_slash_notation&action=edit

wiki-mathjax doesn't run.  Instead, I only get Wikipedia's rendered SVGs.

Tested on the latest Chrome, Version 75.0.3770.100 (Official Build) (64-bit).

**Comment by bgromov** [comment]
I am on exactly same version, on macOS. For me pressing the preview button immediately triggers MathJax rendering.

If you are logged in on Wikipedia, this issue/solution may be relevant to you: #20
