### ISSUE TITLE
Equations displaying incorretly

### ISSUE THREAD

**Issue by themightyoarfish** [bgromov/wiki-mathjax#9]
https://en.wikipedia.org/wiki/Inverse_trigonometric_functions Contains apparently unknown macros. Is this a mathjax issue or again some wikipedia idiosyncrasy?

![screen shot 2015-04-16 at 22 09 24](https://cloud.githubusercontent.com/assets/11613312/7190287/48d862d6-e485-11e4-9d69-b1995ece0e34.jpg)

**Comment by bgromov** [comment]
Thanks, for reporting. New release was just pushed to the Chrome Store.

Well, that is neither MathJax nor Wikipedia issue this time. These macros are not very standard even in LaTeX.

The new version of extension adopted official Wikimedia MathJax config, the same that you can enable in your Wikipedia account. So it is more in sync now with Wikipedia bugs :)
